### ISSUE TITLE
Type Save error: Package Visibility: Type is not visible: <foobar>

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#178] opened 2016-05-19 02:57 UTC
Have an odd issue that I (experienced before as well) think is related to stale synchronization data but am unsure. So my question is where is the synchronization state information stored?

I believe this issue started occurring after another developer modified the file while I was also working on it.  If I disable the Projects 'Use Tooling API deploy path when possible', I can properly save.  Please note I normally work in offline mode so this is a non issue, but with the latest Force.com IDE release I attempted to do otherwise and this surfaced again.

**Comment by danielsokolowski** [comment] 2016-05-27 13:45
This might be an issue with the org, posting these just as extra background info:

- saving same file through Developer Force.com console has the visiblity error
- saving through Eclipse Force.com matadata api works but really slow
- saving through the SF native admin interface is fast at about 5 seconds.

We have a case fileld with SF support.

**Comment by SCWells72** [comment] 2016-05-27 14:07
This is a known issue in the Tooling API:

https://success.salesforce.com/ideaView?id=08730000000l8a5AAA

It's been reported by users of Illuminated Cloud as well.  I've inquired with Greg and Josh as to when/whether it might be fixed as it's quite a nuisance for folks developing projects that use Apex classes from managed packages.  The Tooling API is significantly faster than the Metadata API, but this issue prevents people from using it consistently.  IC users have requested a workaround:

https://bitbucket.org/RoseSilverSoftware/illuminatedcloud/issues/240

but I'd strongly prefer a fix at the source to a workaround.  Hopefully adding these details here will provide additional visibility and raise the chance of a real fix.

**Comment by SCWells72** [comment] 2016-06-08 18:00
FYI, it appears that Salesforce may have fixed the underlying issue. I'm unable to reproduce it in code that previously resulted in this error. Other users have reported similar. Can you guys try to deploy the same code with the Tooling API and see if it's resolved for you as well?

**Comment by danielsokolowski** [comment] 2016-08-23 15:19
Still an issue as of Aug 23, 2016 - I think the tooling API should be disabled by default or would it be possible to add a popup or modify the apex deployment options to advise the end user of this? 

![image](https://cloud.githubusercontent.com/assets/273413/17897277/9806ae72-6921-11e6-8bfd-ba4dd6f0f51e.png)

**Comment by SCWells72** [comment] 2016-08-23 15:40
Interesting that this is still happening, even more so since the primary response to the recent metadata API performance issues in many pods is to use the tooling API as much as possible.  In order to do that realistically, this issue needs to be fixed once and for all.

**Comment by vazexqi** [comment] 2016-08-23 15:43
@danielsokolowski - Are you using the beta or the stable version? Trying to figure out which version of the API you are connecting to.

**Comment by danielsokolowski** [comment] 2016-11-01 16:56
I have updated to latest version commit '0596e85348fe8c338d689051e41d0aac876f07fa' will use and update this thread accordingly.

**Comment by danielsokolowski** [comment] 2016-11-07 19:39
I can confirm this error is still present, possibly only in VF pages; debug log below:

```
INFO [2016-11-07 14:34:12,067] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:34:12,073] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:34:12,080] (BuilderController.java:visit:233) - Resource '/Hammond's 3.0 TSO [PRD]/src/pages/D1_STG_Theme1HomePageTemplate.page' changed
 INFO [2016-11-07 14:34:12,087] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:34:12,092] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:34:19,558] (MarkerUtils.java:applySaveMarker:250) - Applying save error marker: 'src/pages/D1_STG_Theme1HomePageTemplate.page': 'Save error: Type is not visible: cms'
 INFO [2016-11-07 14:34:53,277] (DefaultBuilder.java:build:48) - Project '<REMOVED> [PRD]' has additional Force.com natures - skipping default build
 INFO [2016-11-07 14:34:53,282] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:34:53,287] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:34:53,291] (BuilderController.java:visit:233) - Resource '/<REMOVED> [PRD]/src/pages/ocms_ham_homePage.page' changed
 INFO [2016-11-07 14:34:53,296] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:34:53,300] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:34:56,092] (MarkerUtils.java:applySaveMarker:250) - Applying save error marker: 'src/pages/ocms_ham_homePage.page': 'Save error: Type is not visible: cms'
 INFO [2016-11-07 14:35:40,897] (DefaultBuilder.java:build:48) - Project '<REMOVED> [PRD]' has additional Force.com natures - skipping default build
 INFO [2016-11-07 14:35:40,903] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:35:40,907] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:35:40,912] (BuilderController.java:visit:233) - Resource '/<REMOVED> [PRD]/src/pages/ocms_ham_homePage.page' changed
 INFO [2016-11-07 14:35:40,917] (EquinoxAuthorization.java:addAuthorizationInfo:37) - Saving values in secure storage
 INFO [2016-11-07 14:35:40,921] (ProjectService.java:defaultServerEndpointCheckandFix:1726) - Remove all cached connections and objects related to unsupported API version
 INFO [2016-11-07 14:35:43,771] (MarkerUtils.java:applySaveMarker:250) - Applying save error marker: 'src/pages/ocms_ham_homePage.page': 'Save error: Type is not visible: cms'
```

**Comment by ntotten** [comment] 2019-01-04 15:41
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).

**Closed by ntotten** 2019-01-04 15:41 UTC
