### ISSUE TITLE
New metadata file does not update package.xml

### ISSUE THREAD

**Issue by ImJohnMDaniel** [forcedotcom/idecore#196] opened 2016-07-27 03:14 UTC
When I create a new Apex Class or VF page, the package.xml file is not updated with the new entry.

I am running the following configuration:
- Eclipse: Mars.2 Release (4.5.2) - build id 20160218-0600
- Force.com IDE - v37.0.0.201607262223 (including Debugger option)
- MEGA Lightning - v2.0.0.201607262223
- Java version "1.8.0_31"

**Comment by vazexqi** [comment] 2016-07-27 15:03
@ImJohnMDaniel - I'm assuming you're using the wizard and not creating these manually?

What does your package.xml look like? Are you using wildcards or are you listing the specific names?

More concretely, is the bug that we don't create an entry of the form:

```
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
```

Or that we don't create an entry of the form:

```
    <types>
        <members>MyOIdClass</members>
        <members>MyNewClass</members>
        <name>ApexClass</name>
    </types>
```

If you are not using wildcards, could you share the reasoning behind that? I'm trying to encourage everyone to use wildcards for programmatic stuff, in particular Apex since that makes the analysis possible. If developers start including/excluding classes, then the analysis will be flawed.

**Comment by ImJohnMDaniel** [comment] 2016-07-27 15:48
Hey @vazexqi 

Yes, I am using the wizard.

My package.xml file looks like the following:

    
    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <Package xmlns="http://soap.sforce.com/2006/04/metadata">
        <version>37.0</version>
    </Package>

**Comment by vazexqi** [comment] 2016-07-27 17:20
Do you have exact repro steps?

I'm guessing when you first create the project, the package.xml is actually valid (i.e., contains ApexClass, AuraDefinitionBundle, etc)? What action causes it to lose those information?

Is it just invoking the create new wizard (in online or offline mode)?

Does it matter which wizard you invoke? You mentioned Apex and VF. But what about other ones?

**Comment by ImJohnMDaniel** [comment] 2016-07-27 18:21
@vazexqi - Sure thing.

1. Create new project.  Do not select any metadata items.
2. Use Wizard to create Apex Class. (i.e. "AClass")

....there is no change to the package.xml file.

Even if I hand craft the entry for AClass into the package.xml and then create a new creation a new class ("BClass"), it still does not update the package.xml for the new BClass entry.

"I'm guessing when you first create the project, the package.xml is actually valid (i.e., contains ApexClass, AuraDefinitionBundle, etc)? What action causes it to lose those information?" --  In my case, it had no entries at all.

"Is it just invoking the create new wizard (in online or offline mode)?" -- In this case, the project was "online" and used the create new wizard.

"Does it matter which wizard you invoke? You mentioned Apex and VF. But what about other ones?" -- I don't believe so.  I have had the same experience whether it is Apex or VF.  I tried creating a trigger against Account and the same result.

Does this help?

**Comment by vazexqi** [comment] 2016-07-28 23:30
![screen shot 2016-07-28 at 4 27 57 pm](https://cloud.githubusercontent.com/assets/54414/17232890/47a4c0b8-54e0-11e6-9dab-6b14aa698267.png)

Sorry, took me some time to repro this. So, basically, in the new project wizard, you selected "None" like my screenshot above?

I don't actually know off the top of my head whether this has always been the behavior. I've never actually used the "None" option. I'll need to check the behavior with older versions.

**Comment by ImJohnMDaniel** [comment] 2016-07-28 23:35
@Vazeql

**Comment by ImJohnMDaniel** [comment] 2016-07-28 23:36
Yes that's correct

**Comment by vazexqi** [comment] 2016-07-29 16:01
OK. So I reproduce it as follows:

state| v36 | v37 beta | Comment |
| ---- | ---- | --- | ----|
*Offline* Mode | Nothing added to package.xml | Nothing added to package.xml | Behaves as expected
*Online* Mode | The class/vf is added to package.xml | Nothing added to package.xml | Different behavior

I understand there is a change in behavior. But, to help me prioritize, could you shade some info on the following:

1. What is your use case for preferring the "None" option?
1. Is there a use case for using specific/explicit names in the package.xml vs. just using wildcards?

**Comment by ImJohnMDaniel** [comment] 2016-07-29 20:03
@vazexqi 

1) "What is your use case for preferring the "None" option?"
-- Sometimes, I will setup multiple Eclipse projects to the same org.  I might then use this second project to create scratch/experimental classes/vf/metadata that I don't want mixed in with my primary project for that org.  In this instance, I setup a new eclipse project and chose no metadata so that I could setup some new Lightning files.  I setup another project to test the creation of classes for this task.  There are other use cases where I utilize multiple Eclipse projects for the same org.... just to keep things organized better than simply  "throw everything into one bucket" approach.

2) "Is there a use case for using specific/explicit names in the package.xml vs. just using wildcards?"
-- OH YES. :-)  I almost always explicitly specify the metadata components that I want in my package.xml.  All too often in a SFDC org, there can be fields, Apex, VF, etc of things that do not necessarily belong to the project that you are working on right now.  Especially in large development team product development scenarios, you have several developers in several DE orgs and you use source control and multiple branches to manage the propagation of the code from you org to other developer's orgs on your branch.  You would move code to other branches for testing cycles (and deployments to other testing orgs) and eventually deploy the intended release candidate code changes to the packaging org.  None of those orgs are connected, and I need to make absolutely certain that only the project related code makes into source control.  By explicitly specifying the package.xml, the entire development team only works with the metadata components that are related to the project.  No "stray" classes or obsolete classes creep in and the end result is "clean" and deployed to the packaging org (which was stripped bare of any extraneous code at the start of the project).

Also, explicitly setting metadata in packaging.xml helps with performance in large orgs.  I don't have to wait for Eclipse to download/refresh every file from the org.  I just get it to work with only the files that I am interested in.

Make sense?

**Comment by ImJohnMDaniel** [comment] 2016-11-05 23:34
@vazexqi 

Just curious.  Is there any progress on this?

Cheers!

**Comment by JohnMcCarvill** [comment] 2017-12-13 19:42
I am also having the same exact issue with Eclipse Oxygen and version 37 and 38 of the Force.com IDE.  I create empty projects and when I add new metadata, (Apex classes, triggers, etc.) it is not updating the package.xml file.

I am forced to continue to use Eclipse Mars and Force.com  IDE where this works correctly and package.xml is updated with new project metadata as it is added to the IDE.

This will prevent me from moving forward with newer versions of Force.com IDE.

**Comment by JohnMcCarvill** [comment] 2018-07-04 12:02
Still hoping to get a solution to this.  I cannot advance beyond the Force.com IDE v36 because adding new metadata to a project does not automatically update the package.xml in the Force.com IDE version 37 or 38.

This is very frustrating and time consuming to update the package.xml manually for every new project metadata being added.  It is much faster working in v36 where it correctly adds the metadata to the package.xml file, however, very soon, we will need support for the newer API in Eclipse.

I have searched for possible fixes to this via custom settings or config, but I have not found anything.

Please resolve this issue in the next release of the Force.com IDE.  I believe it is the best development tool for Salesforce, but really need the package.xml to be correctly maintained in order to use it.

**Comment by ntotten** [comment] 2019-01-04 15:40
The Force.com IDE is in maintenance only mode and will be discontinued on Oct. 12, 2019. As such we are no longer be tracking issues on Github. The repository will remain open source but will be archived soon. We recommend moving to the [Salesforce Extensions for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode). See this [migration guide on how to move from Force.com IDE to VS Code](https://github.com/forcedotcom/salesforcedx-vscode/wiki/Migrate-From-Forcecom-IDE-to-Visual-Studio-Code)

For more details on the announcement to deprecated the Force.com IDE see [this post](https://developer.salesforce.com/blogs/2018/12/the-future-of-salesforce-ides.html).

**Closed by ntotten** 2019-01-04 15:40 UTC
Labels: lightning
