### ISSUE TITLE
CRITICAL!!! Code is being overwritten without giving any conflicts!!

### ISSUE THREAD

**Issue by pranavraulkar** [forcedotcom/idecore#66] opened 2014-09-05 19:10 UTC
In the latest 31.x update (I updated from v29.x Eclipse Kepler)  the code is being completely overwritten when we do save on any component. It does not give any conflicts and completely overwrites the code on the server!!

**Comment by BryanLL** [comment] 2015-12-02 03:02
Please, this *has* to be fixed! Even if I use the "Synchronize with server" to update my local copy, til I go through a dozen changes or so and then save the results to the server, someone else could've have already uploaded another change. We have several developers working simultaneously and independently. We're not always aware of what code the other projects is impacting.

The IDE says it's doing a (lengthy) "Synchronize check against server" so it should at least work properly.  The Force.com IDE Developer Guide states "If the metadata components on the server have changed since your last save or refresh and a conflict is detected, you may be asked to enter the Synchronize with Server view."

https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/ide_pro_save_to_server.htm

**Comment by BryanLL** [comment] 2016-02-09 18:44
Still broken!

I've got two computers with Eclipse Kepler and the Force.com IDE to simulate multiple developers. I update a VF page and save to the server on computer A. Then I make a change to the same page without having refreshed my local copy on computer B and save to the server. It doesn't tell me that the server contains a newer version than what I last downloaded. Computer A is running Force.com 35.0.0.201512211056 and computer B is running version 36.0.0.201601081632. I've tried it with the tooling API checkbox checked and without. I'd read that working in offline mode forces a synchronization check, but it doesn't. 

If I had a viable alternative IDE, I'd use it. Any ideas? I tried SublimeText3 w/ MavensMate, but after creating my development org project, it immediately says it can't open it. So that's a no go.

**Comment by vazexqi** [comment] 2016-02-10 00:30
https://vimeo.com/154797828 shows the conflict detection working. 

@BryanLL: If that is not working for you, could you provide some repro steps?

"Currently, we [prescribe](http://www.salesforce.com/us/developer/docs/dev_lifecycle/salesforce_development_lifecycle.pdf) that only one developer works on each DE org and then merge using a traditional SCM. That's why detecting conflicts is not something that we added for the IDE using the Tooling API. "

As mentioned in the earlier comments, you need to uncheck using the Tooling API to use the old Metadata API behavior. I am not inclined to put the synchronization check into the Tooling API.

@danielsokolowski  - I will need to investigate more about your Git issue.

**Comment by BryanLL** [comment] 2016-02-11 16:35
@vazexqi : Thanks for replying. 
How are you getting the error indication when you just save locally? 

What I remember from when I first started with an old Force.com IDE a year ago was that I used to see the conflict message in a dialog window when I chose "Save to server". So that's where I was looking for it, but it no longer does that.

How do I get the synchronization check to occur? I've tried while working "offline" and "online" and I don't get a red-x and entry in the error list either way. 

[https://youtu.be/OQDAM5HW7ps ](url)

--Bryan

**Comment by vazexqi** [comment] 2016-02-11 16:42
@BryanLL 

I watched your YouTube video. I noticed that you right-clicked and select 'Save to Server'.

In my case, I had two things different:

1) My project was in online mode. Right click the project, Force.com > Work online.
2) Edit the file
3) Ctrl + S to save. Or File > Save. Or use the toolbar icon.

I will investigate what you mentioned about "Save to Server" right-click menu doing an explicit sync check. It might be a regression.

**Comment by BryanLL** [comment] 2016-02-11 16:50
I could re-do the video in online mode. It works (or in this case fails) just the same.
Do you have "Build Automatically" checked? I had to turn this off when I was attempting to use eGit and it appeared to be overwriting code on the server when I switched branches. I've since abandoned eGit for my dev org.

**Comment by vazexqi** [comment] 2016-02-11 16:53
@BryanLL - I do have Project > Build Automatically checked. What happens if you turn that on?

Also, could you or @danielsokolowski provide more details on the eGit issue. I don't use eGit, preferring to use the command line for Git. If one of you can tell me how to repro "I agree that this is a critical issue as it is also apparent when doing a merge resolution in GIT, overwriting the local file triggers save to the server behaviour" that would be good.

**Comment by BryanLL** [comment] 2016-02-11 22:52
Regarding Build Automatically, I'll have to take some time to set up a test. I was overwriting code completely unaware, so I'll only turn that on for a controlled test and it'll take me a while to completely refresh from my dev org before I'm comfortable doing that.

FWIW, I just had an internet outage and my "Save to Server" operation gave me a message that it could not perform the synchronization check and I may be out of sync. So it seems like it thinks it's supposed to be checking, but either isn't or is ignoring the results.

I'll let you know when I get a chance to try the Build Automatically setting.

**Comment by vazexqi** [comment] 2016-02-12 18:19
@BryanLL - I tried it today. "Build Automatically" has to be turned on for Ctrl + S / File > Save/ Toolbar icon to save to server and detect conflict.

See https://vimeo.com/155151858

Let me investigate the "Save to Server" and see why the conflicts are not being surfaced.

**Comment by vazexqi** [comment] 2016-02-16 16:47
@BryanLL - I've fixed the behavior and the code should be committed shortly. It will be available in the beta channel shortly. Just FYI, we just did a major upgrade so you need to use Eclipse Mars and Java 8 to run the one in the beta channel. This is the plan moving forward.

https://vimeo.com/155548599

**Comment by BryanLL** [comment] 2016-02-16 20:07
Wonderful! Thank you!!!

**Closed** 2016-02-18 20:59 UTC

**Comment by lcoffin** [comment] 2016-03-04 21:40
"As mentioned in the earlier comments, you need to uncheck using the Tooling API to use the old Metadata API behavior. I am not inclined to put the synchronization check into the Tooling API."

I have to say that this decision is really, really bad. At least coupled with having the "Use Tooling API" selected as a default. This now means that unless a developer is familiar with this specific issue, a new Eclipse install will now by default blow away any changes other developers have made. Which, I'd say 0.001% of developers will know to do this until it is too late.

For existing developers who have been working in Eclipse for years, it is an ingrained expectation that changes made on the server are safe from being overwritten unless the user uses an explicit 'Save to Server'. This change when upgrading, or installing a fresh copy, will not be expected.

The Salesforce docs -- https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/ide_pro_save_to_server.htm -- also explicitly indicates that a conflict check will happen.

"Currently, we prescribe that only one developer works on each DE org and then merge using a traditional SCM. That's why detecting conflicts is not something that we added for the IDE using the Tooling API. "

I appreciate you think this is the way it *should* happen, but this is completely unrealistic. There's no way I'm going to try to ask my developers to spin up a DE org and try to copy over all the relevant code, packages, objects, etc. that any given change might need -- for anything but the most *basic* code/environment. And we gave up on trying to use an SCM on our projects about two dozen projects ago (two dozen for me, hundreds for my company). Way way too difficult to set up and maintain for hundreds of projects.

In my current project, for example, in just my particular track, we are working with an Apttus installation, coupled with Revitas, coupled with custom integrations, and constantly evolving business requirements (read SFDC config changes). All of those packages need to be installed, configured on both ends to point to the correct servers, configured with all the right product records, selling configurations, etc. There's no way anyone can realistically try to develop code touching all these different pieces in a dev org or even a separate sandbox, then try to merge back in to the main sandbox. Not without loosing months of man-hours trying to keep everything in sync.

So, it really really saddens me to see someone "in charge" of this critical code trying to force a completely unrealistic expectation on users. Why make the decision to make a really really unsafe situation the standard, OOB setup? If you want to make it an option to disable the check, I'm fine with that, but out of the box, the Force.com IDE should do the check no matter what API is being used. If you really really don't want to make it part of the Tooling API "path", then don't make the Tooling API the default. Make safety the standard and allow users to opt-in to a non-safe environment instead.

(I'm sure your intentions of trying to push people to developing in a DE comes from a good place -- I understand trying to isolate developer changes until they are ready, but this just isn't realistic to do 100% of the time when time and money are on the line given how difficult it is to replicate environments within the Salesforce world. I'm not trying to piss you off -- I do appreciate the work being done to maintain this code -- I'm just trying to explain the world that I work in -- fast changing, very very complex, with large teams that are changing on a regular basis, quite often with developers with very different levels of experience.)

**Comment by vazexqi** [comment] 2016-03-04 22:24
@lcoffin - Thanks for the detailed feedback. I'll bring this up with our team. 

I think the main issue is, as you have identified, "how difficult it is to replicate environments within the Salesforce world". We are working on improving this area.

However, your other points about "fast changing, very very complex, with large teams that are changing on a regular basis, quite often with developers with very different levels of experience" is valid.

**Comment by lcoffin** [comment] 2016-03-04 22:34
@vazexqi Great, thanks Nick. I really appreciate it!

**Comment by danielsokolowski** [comment] 2016-03-05 02:09
My development experience is that of Lawrence and I agree with his 
points. I think it's a good compromise to make it an option and enabled 
by default. Perhaps to increase the option's visibility it could be also 
added to the new project creation wizard with an explanation that the 
speed increase comes at a cost of collision detection.

On 2016-03-04 4:40 PM, Lawrence Coffin wrote:
>
> "As mentioned in the earlier comments, you need to uncheck using the 
> Tooling API to use the old Metadata API behavior. I am not inclined to 
> put the synchronization check into the Tooling API."
>
> I have to say that this decision is really, really bad. At least 
> coupled with having the "Use Tooling API" selected as a default. This 
> now means that unless a developer is familiar with this specific 
> issue, a new Eclipse install will now by default blow away any changes 
> other developers have made. Which, I'd say 0.001% of developers will 
> know to do this until it is too late.
>
> For existing developers who have been working in Eclipse for years, it 
> is an ingrained expectation that changes made on the server are safe 
> from being overwritten unless the user uses an explicit 'Save to 
> Server'. This change when upgrading, or installing a fresh copy, will 
> not be expected.
>
> The Salesforce docs -- 
> https://developer.salesforce.com/docs/atlas.en-us.eclipse.meta/eclipse/ide_pro_save_to_server.htm 
> -- also explicitly indicates that a conflict check will happen.
>
> "Currently, we prescribe that only one developer works on each DE org 
> and then merge using a traditional SCM. That's why detecting conflicts 
> is not something that we added for the IDE using the Tooling API. "
>
> I appreciate you think this is the way it /should/ happen, but this is 
> completely unrealistic. There's no way I'm going to try to ask my 
> developers to spin up a DE org and try to copy over all the relevant 
> code, packages, objects, etc. that any given change might need -- for 
> anything but the most /basic/ code/environment. And we gave up on 
> trying to use an SCM on our projects about two dozen projects ago (two 
> dozen for me, hundreds for my company). Way way too difficult to set 
> up and maintain for hundreds of projects.
>
> In my current project, for example, in just my particular track, we 
> are working with an Apttus installation, coupled with Revitas, coupled 
> with custom integrations, and constantly evolving business 
> requirements (read SFDC config changes). All of those packages need to 
> be installed, configured on both ends to point to the correct servers, 
> configured with all the right product records, selling configurations, 
> etc. There's no way anyone can realistically try to develop code 
> touching all these different pieces in a dev org or even a separate 
> sandbox, then try to merge back in to the main sandbox. Not without 
> loosing months of man-hours trying to keep everything in sync.
>
> So, it really really saddens me to see someone "in charge" of this 
> critical code trying to force a completely unrealistic expectation on 
> users. Why make the decision to make a really really unsafe situation 
> the standard, OOB setup? If you want to make it an option to disable 
> the check, I'm fine with that, but out of the box, the Force.com IDE 
> should do the check no matter what API is being used. If you really 
> really don't want to make it part of the Tooling API "path", then 
> don't make the Tooling API the default. Make safety the standard and 
> allow users to opt-in to a non-safe environment instead.
>
> (I'm sure your intentions of trying to push people to developing in a 
> DE comes from a good place -- I understand trying to isolate developer 
> changes until they are ready, but this just isn't realistic to do 100% 
> of the time when time and money are on the line given how difficult it 
> is to replicate environments within the Salesforce world. I'm not 
> trying to piss you off -- I do appreciate the work being done to 
> maintain this code -- I'm just trying to explain the world that I work 
> in -- fast changing, very very complex, with large teams that are 
> changing on a regular basis, quite often with developers with very 
> different levels of experience.)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/forcedotcom/idecore/issues/66#issuecomment-192479834>.
>

-- 
Daniel Sokolowski
http://webdesign.danols.com/
Office: 613-817-6833
Kingston, ON K7L 1H3, Canada


Notice of Confidentiality:
The information transmitted is intended only for the person or entity to which it is addressed
and may contain confidential and/or privileged material. Any review re-transmission dissemination
or other use of or taking of any action in reliance upon this information by persons or entities
other than the intended recipient is prohibited. If you received this in error please contact
the sender immediately by return electronic transmission and then immediately delete this
transmission including all attachments without copying distributing or disclosing same.

**Comment by BryanLL** [comment] 2016-04-12 13:55
Is there a way to download this yet? When I check for updates, the version that shows up as available is 36.0.0.201601221512.

**Comment by BryanLL** [comment] 2017-01-30 15:43
Finally got around to upgrading to Eclipse Mars and installing the latest Force.com IDE. THANK YOU SO MUCH for fixing this!!! The sync. check is quick and working great for me now.
