### ISSUE TITLE
[BUG] Does not exist: com.salesforce.ide.debug.core.sourceLocator.apex (orignally: Missing right click 'Run Test' context menu option)

### ISSUE THREAD

**Issue by danielsokolowski** [forcedotcom/idecore#108] opened 2015-05-13 13:47 UTC
I have just updated to the latest Beta (Version: Spring '15 (33.0.0)) and am unable to run individual tests on classes - right clicking on is missing the 'Run Test' option, I only get, refresh, save, and synchronize with server and Show in Salesforce Web.

**Comment by DatGuyJonathan** [comment] 2015-05-13 14:21
Hi @danielsokolowski , we made some changes to Apex test runner in Beta. Please check out the release notes here: https://github.com/forcedotcom/idecore/wiki/Changes-in-Force.com-IDE-Beta-Version-34.0.0.20150511

**Comment by vazexqi** [comment] 2015-05-13 15:01
@danielsokolowski Thanks for the feedback and for trying out the Beta version. As @DatGuyJonathan mentioned, we have changed the way we launched tests to be more consistent with how the Java for Eclipse tools do it, i.e., via a launch configuration.

That said, we should probably add a Launch As > Apex Test ala Java for Eclipse as well. We will use this bug to keep track of that.

If you have any other feedback about the new run test feature, please let us know.

**Comment by danielsokolowski** [comment] 2015-05-13 19:23
No problem, glad to help with improving the Force.com IDE - thanks for your hard work. 

I was am missing 'Run' button to get to the 'Run Configurations' option, I have spent the last 20 minutes looking for it - it is available the Debug perspective which I had to activate. 

![missing-run-configurations-button-found-in-debug-perspective](https://cloud.githubusercontent.com/assets/273413/7619019/002921f6-f984-11e4-959f-7f3ff044e291.png)

**Comment by danielsokolowski** [comment] 2015-05-13 19:27
It looks that the Force.com perspective is missing it, I am on a clean install or Eclipse (MARS) and latest Force.com IDE beta. 
![force-ide-disabled-run-lunch-button](https://cloud.githubusercontent.com/assets/273413/7619118/9ee926d8-f984-11e4-9181-a64860c1d001.PNG)

**Comment by danielsokolowski** [comment] 2015-05-13 19:34
Also it's not working, selecting all or specific class gives below error - NOTE you can not clear a class (swtich to ALL classes) if you select a class once.

Would you have a link to the previous beta version please?

![force-com-issue-with-the-new-test-runner](https://cloud.githubusercontent.com/assets/273413/7619271/7db224f0-f985-11e4-86a8-42ade92cdfb4.png)

**Comment by danielsokolowski** [comment] 2015-05-13 19:45
Anyone looking for the older version, they can be found here: http://media.developerforce.com/force-ide/eclipse42

Perhaps could we please add this information to this page just in people need to revert? : https://github.com/forcedotcom/idecore/wiki/Downloading-the-Beta-Version-of-the-Force.com-IDE

**Comment by vazexqi** [comment] 2015-05-13 19:50
@danielsokolowski I'm going to pull out the issue with Mars not showing the run dialog into a separate issue. I can reproduce it but it seems to be Mars specific. And it happens when you open the editor.

If you are on the Project Explorer, you can see that menu.

I don't see that issue for Juno or Kepler.

**Comment by vazexqi** [comment] 2015-05-14 05:44
Addressed by 453c916e4c842997c11cfe361be06bc8b700629a

The issue was that we were bundling the source locator as part of Force.com IDE Debugger instead of just Force.com IDE. On further investigation it turns out we did not need to use the source locator for the run tests functionality so we also removed that dependency.

**Comment by vazexqi** [comment] 2015-05-14 23:40
@danielsokolowski This has been fixed in the latest beta.

**Closed by vazexqi** 2015-05-14 23:40 UTC
